
#+++++++++++++++++++++++++ Production Image Path ++++++++++++++++++++++++++++++

ABOUT_US=/var/www/images/shebacms/aboutus-file/
CMS=/var/www/images/shebacms/cms-image/
GALLERY=/var/www/images/shebacms/gallery-image/
MEMBER=/var/www/images/shebacms/member-image/
NOTICE=/var/www/images/shebacms/notice-file/
STUDENT=/var/www/images/shebacms/student-file/
SYLLABUS=/var/www/images/shebacms/syllabus-file/



#++++++++++++++++++ Dev / Local Server Image path ++++++++++++++++++++++++++++++++


#CMS=/home/centos/SonaliSikkha/images/cms-app/cms-image/
#GALLERY=/home/centos/SonaliSikkha/images/cms-app/gallery-image/
#MEMBER=/home/centos/SonaliSikkha/images/cms-app/member-image/
#NOTICE=/home/centos/SonaliSikkha/images/cms-app/notice-file/
#ABOUT_US=/home/centos/SonaliSikkha/images/cms-app/aboutus-file/
#STUDENT=/home/centos/SonaliSikkha/images/cms-app/student-file/
#SYLLABUS=/home/centos/SonaliSikkha/images/cms-app/syllabus-file/




