# General configurations

#spring.profiles.active=dev
spring.profiles.active=prod
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
spring.http.multipart.max-file-size=15MB
spring.http.multipart.max-request-size=15MB
#
#logging.level.root=ERROR
#logging.level.org.springframework.web=ERROR
#logging.level.org.hibernate=ERROR